sudo: required
services:
  - docker

before_install:
  - docker build -t orarnon/docker-react -f Dockerfile.dev .

script:
  - docker run -it orarnon/docker-react npm run test -- --coverage

deploy:
  - provider: elasticbeanstalk
  - region: 'us-east-1'
  - app: 'docker-react'
  - env: 'DockerReact-env'
  - bucket_name: 'elasticbeanstalk-us-east-1-032106861074'
  - bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_key_id: 
    secure: "$AWS_ACCESS_KEY"